pipeline {

    agent { label 'maven-3.6.3-jdk-11' }

    options {
        skipDefaultCheckout true
    }

    stages {
        stage ("Compile") {
            steps {
                container('maven') {
                    checkout scm
                    withMaven(globalMavenSettingsConfig: 'maven-settings',
                              options: [junitPublisher(disabled: true, healthScaleFactor: 1.0)],
                              publisherStrategy: 'EXPLICIT') {
                        sh 'mvn clean compile -DskipTests=true'
                    }
                }
            }
        }
        stage ("Test") {
            steps {
                container('maven') {
                    withMaven(globalMavenSettingsConfig: 'maven-settings',
                              options: [junitPublisher(disabled: true, healthScaleFactor: 1.0)],
                              publisherStrategy: 'EXPLICIT') {
                        sh 'mvn test -DskipTests=false'
                    }
                }
            }
        }
        stage ("SonarQube") {
            steps {
                container('maven') {
                    withSonarQubeEnv('SonarQube') {
                        withMaven(globalMavenSettingsConfig: 'maven-settings',
                              options: [junitPublisher(disabled: true, healthScaleFactor: 1.0)],
                              publisherStrategy: 'EXPLICIT') {
                            sh 'mvn -DskipTests=true -Dsonar.host.url=${SONAR_HOST_URL} sonar:sonar'
                        }
                    }
                }
            }
        }
        stage ("Package") {
            steps {
                container('maven') {
                    withMaven(globalMavenSettingsConfig: 'maven-settings') {
                        sh 'mvn package -DskipTests=true'
                    }
                }
            }
        }
        stage ("Publish to Artifactory") {
            steps {
                container('maven') {
                    script {
                        artifactId = readMavenPom().getArtifactId()
                        artifactVersion = readMavenPom().getVersion()
                    }
                    rtServer (
                        id: 'Artifactory'
                    )
                    rtUpload (
                        serverId: 'Artifactory',
                        spec: """{
                                "files": [
                                {
                                    "pattern": "target/${artifactId}-*.jar",
                                    "target": "maven-local-snapshots/org/springframework/samples/${artifactId}/${artifactVersion}/"
                                },
                                {
                                    "pattern": "pom.xml",
                                    "target": "maven-local-snapshots/org/springframework/samples/${artifactId}/${artifactVersion}/${artifactId}-${artifactVersion}.pom"
                                }
                                ]
                            }"""
                    )
                    rtPublishBuildInfo serverId: 'Artifactory'
                }
            }
        }
    }
}
